apiVersion: v1
kind: Service
metadata:
  name: edu-web-beta
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: edu-web-beta